// Code generated by hertz generator.

package videos

import (
	"HuaTug.com/cmd/api/router/authfunc"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopublishcancleMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _videopublishcompleteMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _videopublishstartMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _videopublishuploadingMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videofeedlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopopularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosearchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videodeleteMw() []app.HandlerFunc {

	return authfunc.Auth()
}
func _visitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoidlistMw() []app.HandlerFunc {
	return authfunc.Auth()
}
