services:
  mysql:
    image: mysql:latest
    container_name: kitex_mysql    
    volumes:
      - ./config/mysql/:/docker-entrypoint-initdb.d/ 
    environment:
      - MYSQL_DATABASE=TikTok
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - "3306:3306"
    privileged: true

    networks:
      - docker_net

  redis:
    image: redis:latest
    container_name: kitex_redis
    ports:
      - "6379:6379"
    volumes:
      - ./config/cache/redis/redis.conf:/usr/local/etc/redis/redis.conf  
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - docker_net

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq_kitex
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - docker_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - ./config/Es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - docker_net
    depends_on:
      - elasticsearch

  etcd:
    image: bitnami/etcd:3.5.9
    container_name: etcd01
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd01
      - ETCD_DATA_DIR=/bitnami/etcd/data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd01:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=etcd01=http://etcd01:2380
    volumes:
      - ./config/etcd:/bitnami/etcd/data
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - etcd_network


  work:
    image: work:latest
    container_name: Micro_Server
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - elasticsearch
      - kibana
    profiles: 
    - release
    ports:
      - 8000:8888
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge

  etcd_network:
    driver: bridge
